### ISSUE TITLE
[Suggestion] more survival feeling.

### ISSUE THREAD

**Issue by Taknax** [DAQEM/JobsPlus-Archive#1]
Cool would be a jobbook (or maybe a paper = a contract) to monitize your stuff, instead just of /commands. A craftable Jobbook or Contractpaper would make it much more survival. Maybe with possiblity to choice up to 3 classes (multiple classes). For the first class a Contractpaper is needet. for more classes a Jobbook?
I like this mod and it would get a place in my upcoming modpack.

**Comment by DAQEM** [comment]
Something like this (a book to manage everything) is on my todo list, thank you for the suggestion though, now I know people actually want this.

**Comment by Taknax** [comment]
Do you consider a book, or it is not more on the todo list?
I ask because i am before uploading my pack and Jobs+ would get a slot.

**Comment by DAQEM** [comment]
You can now press J to open the GUI. No need for a book anymore.
