### ISSUE TITLE
Smith - 'Enchantment from item to Book' Bugged

### ISSUE THREAD

**Issue by Jorgee9001** [DAQEM/JobsPlus-Archive#10]
Minecraft 1.18.1
Forge 39.0.89
Mod version 0.2.8

When taking the Smith job perk 'Enchantment from item to Book', placing a tool in an anvil along with literally any other object will give the enchanted book; no book required. This also makes it impossible to repair tools with their material or combine them.

This can be temporarily fixed by disabling the job perk.

**Comment by DAQEM** [comment]
This issue was fixed in version 0.3.0. 1.18.1 is discontinued.
