### ISSUE TITLE
[1.18.2] Vein Miner not working with Tinker's Pickaxes

### ISSUE THREAD

**Issue by ffuentesm** [DAQEM/JobsPlus-Archive#12]
jobsplus-0.3.0.jar
Mantle-1.18.2-1.9.20.jar
TConstruct-1.18.2-3.5.0.17.jar
Forge: 40.1.19

When using the Vein Miner ability with the Tinker's pickaxe, it does not activate.

**Comment by DAQEM** [comment]
`isCorrectToolForDrops()` Is used to check if the tool used drops items when the block is broken. If this is not case, veinminer wont work. So, the problem must lie with Tinkers.

**Comment by KnightMiner** [comment]
[But you hardcode to the vanilla `PickaxeItem`](https://github.com/DAQEM/JobsPlus/blob/1.19.1/src/main/java/me/daqem/jobsplus/events/jobs/MinerEvents.java#L80). That is entirely unneeded, but if you must check the tool type use tool actions.
