### ISSUE TITLE
[1.18.2] Bag crafting upgrade not working

### ISSUE THREAD

**Issue by ffuentesm** [DAQEM/JobsPlus-Archive#15]
Mod: jobsplus-0.3.0.jar
Forge: 40.1.25

As you can see, I got the requirements to craft the bag, but it does not work
![image](https://user-images.githubusercontent.com/44974827/170380577-c62f4dcf-ec96-45b1-9a3f-40342f07ed62.png)
![image](https://user-images.githubusercontent.com/44974827/170380592-b731ab26-1d80-4a58-99fe-56bb7fc7aae0.png)
![image](https://user-images.githubusercontent.com/44974827/170380608-97218a30-8b0d-4501-822a-669303c9dbcb.png)

**Comment by DAQEM** [comment]
Fixed in next update: DAQEM/JobsPlus@24639b99104c004a04529030f6095874bc5e862d
