### ISSUE TITLE
Crash when placing Mekanism cardboard box

### ISSUE THREAD

**Issue by echilda** [DAQEM/JobsPlus-Archive#17]
When placing the cardboard box on any object, including an air block, an error occurs from AlechemyEvents occurs resulting in a game crash. Not sure if the issue is with Jobs+ or Mekanism.

[crash-2022-05-29_14.51.57-client.txt](https://github.com/DAQEM/JobsPlus/files/8793457/crash-2022-05-29_14.51.57-client.txt)

**Comment by DAQEM** [comment]
Fixed in next update.
