### ISSUE TITLE
"invalid signature" When sending chat messages

### ISSUE THREAD

**Issue by Dak-Darklighter** [DAQEM/JobsPlus-Archive#18]
Having an issue where when we send chat messages the wont send and just errors it in console.

[19:58:17] [Server thread/WARN] [minecraft/ServerGamePacketListenerImpl]: Dak_Darklighter sent message with invalid signature: 'HUNTER Dak_Darklighter > '

Only  /msg, /tell and /me works for player and admins can still use /say

**Comment by DAQEM** [comment]
Disabled the chat prefix feature. Due to Mojangs report systems, every message sent has to be "signed". Because this might change a lot of times, I'm not going to fully fix it for now.
