### ISSUE TITLE
[1.18.2] Carry On mod

### ISSUE THREAD

**Issue by nitbe** [DAQEM/JobsPlus-Archive#19]
There will be problems with carry on mod and jobs，When you pick up the chest with your hand and put it down, the backpack will get a new chest（I think it may be caused by the profession of architect

 

Trigger condition: when you have a hugh backpack in your backpack, then lift the chest and put it down

**Comment by DAQEM** [comment]
You cannot put a backpack inside of another backpack.
Please clarify what you mean so I can fix it.
