### ISSUE TITLE
1.18 Freeze Walker Builder Job

### ISSUE THREAD

**Issue by ffuentesm** [DAQEM/JobsPlus-Archive#2]
Apparently, the Freeze Walker boot enchantment count as block placing for the Builder job.  
So every time I walk on water I get exp for the job
![image](https://user-images.githubusercontent.com/44974827/147399416-4cbf515e-2b06-4636-8345-f2bca83ca6a4.png)

**Comment by DAQEM** [comment]
Thank you for reporting this issue, This issue will be fixed in the next update.

**Comment by DAQEM** [comment]
Fixed.
