### ISSUE TITLE
[1.18.2] Jobs guide book spam

### ISSUE THREAD

**Issue by TobyVanBuynder** [DAQEM/JobsPlus-Archive#25]
I'm running a Forge server with the latest Jobs+ build for 1.18 (0.4.0).

Everytime we restart the server after 24 hours or longer, I get a new guide book (Server gave 1x to player) to the point that we have over a stack of these books in just 2 weeks of playing.

Please add a config option to disable this

**Comment by DAQEM** [comment]
Fixed by 07a69860100c2f20be8f5f728e90826380e5d765
