### ISSUE TITLE
Can't use effect text will not leave screen.

### ISSUE THREAD

**Issue by MissSweetViolet** [DAQEM/JobsPlus-Archive#26]
I hit the vain mine key at one point by mistake, however now the text that I can't use it yet will not leave the screen. I can only get it to go away is by disabling the mod and as soon as I reenable it, it comes back even without pressing anything, it just will not go away. I'm playing on 1.19.2 with the most recent version of the mod from CurseForge. (Edit; some text from another mod popped up, and I noticed it went away, but not sure what triggered it to go away.)
![2022-08-31_16 23 26](https://user-images.githubusercontent.com/101423293/187778063-d1fb30f2-2009-4f54-aec3-22751e9443d2.png)

**Comment by DAQEM** [comment]
Its not the veinminer, its an effect. Is there anything givi g you haste II constantly? Like a modded beacon or something?

**Comment by MissSweetViolet** [comment]
Not that I can see, though playing more, I did notice that it seems to only appear and stick when a lunar event is happening with Enhanced Celestials, and it goes away when the lunar event ends.

**Comment by DAQEM** [comment]
Caused by lunar event.
If you want this to go away. set `allow_all_effects` to `true` in the `jobsplus-server.toml`.

**Comment by parmstr2** [comment]
Having this same problem in 1.18.2 but the config doesn't have that option is there any other way to fix it?
