### ISSUE TITLE
Bug with create

### ISSUE THREAD

**Issue by DoctorMage** [DAQEM/JobsPlus-Archive#30]
Mods involved
create-1.18.2-0.5.0.e
flywheel-forge-1.18.2-0.6.5
jei-1.18.2-9.7.1.255
jobsplus-0.4.0

If you use the wrench on any block from create you will gain exp for the builder job
https://streamable.com/fn7t1s

**Comment by DAQEM** [comment]
Thank you for the extensive report.
Fixed for the latest 1.19.2 version.

**Comment by DoctorMage** [comment]
Glad to hear any plans on updating for 1.18.2?
