### ISSUE TITLE
How do I disable alchemist's flying potion

### ISSUE THREAD

**Issue by cocojiang39** [DAQEM/JobsPlus-Archive#34]
Nice setup but too unbalanced for me

**Comment by DAQEM** [comment]
Need to add a config option for this.

**Comment by exdj158** [comment]
the mod is perfect but also need custom config and more balance

**Comment by DAQEM** [comment]
> the mod is perfect but also need custom config and more balance

What about the mod would you consider unbalanced? Please let me know ;)

**Comment by exdj158** [comment]
flying potion and unbreakable are like op's power,don't you think so?Maybe can replace these with other superpower？

**Comment by DAQEM** [comment]
Depends on the modpack you play. I think gaining Smith level 100 is not easy, so you deserve unbreakable tools. And obtaining a nether star for 10 mins of flight seems fair. If it is too easy to get nether stars, your modpack probably contains a ring of flight anyway 🤷‍♂️. But I'm working on a config option for them right now.

**Comment by exdj158** [comment]
> 取决于你玩的模组包。 我认为获得史密斯 100 级并不容易，所以你应该拥有牢不可破的工具。 并且获得一个 10 分钟飞行的下界之星似乎是公平的。 如果太容易获得下界之星，那么您的模组包可能无论如何都包含一个飞行环 🤷‍♂️ . 但我现在正在为他们设计一个配置选项。

Okay you are right, Thank you for developing this mod

**Comment by exdj158** [comment]
> 取决于你玩的模组包。 我认为获得史密斯 100 级并不容易，所以你应该拥有牢不可破的工具。 并且获得一个 10 分钟飞行的下界之星似乎是公平的。 如果太容易获得下界之星，那么您的模组包可能无论如何都包含一个飞行环 🤷‍♂️ . 但我现在正在为他们设计一个配置选项。

Can  you add a configuration to disable a job?
