### ISSUE TITLE
[1.19.2] - Crash in singleplayer world on loading in

### ISSUE THREAD

**Issue by ToxinZangoose** [DAQEM/JobsPlus-Archive#35]
My forge version is the latest, (43.1.47)
I loaded a premade world and saw the skybox for a full 2 seconds before it crashed.

Here is the crash log below.
[crash-2022-10-25_12.51.09-client.txt](https://github.com/DAQEM/JobsPlus/files/9862722/crash-2022-10-25_12.51.09-client.txt)

Love this mod to bits, hope this helps with debugging!

**Comment by DAQEM** [comment]
I just uploaded a new jar to CurseForge. Hope that fixed the issue!
