### ISSUE TITLE
new error.. latest update makes all jobs+ items uncraftable

### ISSUE THREAD

**Issue by DAQEM** [DAQEM/JobsPlus-Archive#36]
new error.. latest update makes all jobs+ items uncraftable

__Originally posted by @erazare in https://github.com/DAQEM/JobsPlus/issues/28#issuecomment-1292555738__

**Comment by jinkhya** [comment]
Hello!
same problem here, also I dunno if it's related but I can't even see the recipes in the construction table, and on the hammer it says I need lvl 101
![image](https://user-images.githubusercontent.com/10158963/198904734-785ced04-9612-430f-82b3-70ab89323743.png)
![image](https://user-images.githubusercontent.com/10158963/198904724-95de643f-9a7d-40d6-b403-c8a57b3e4241.png)

**Comment by jinkhya** [comment]
well all items from the mod say I need level 101 of each job :)

**Comment by DAQEM** [comment]
What other mods are you using?

**Comment by jinkhya** [comment]
I am SUPER confused, I reloaded the pack today and now the tooltip tells me the right levels for the different tiers, I can see the recipes in the table, and I can craft just fine. I'm playing on a server and the server hasn't restarted. Yesterday when I was trying to do the same thing I had restarted the server and the client a couple times and it never worked lol even in single player. Could it be an event thing for halloween breaking it ?... I really don't see why it started working :')

**Comment by DAQEM** [comment]
I have no idea, might have been 🤷‍♂️. I'll close this for now.

**Comment by jinkhya** [comment]
Hello again, I wonder if [that's](https://github.com/DAQEM/JobsPlus/issues/39) the issue I'm having in 1.19 ? I still get the lvl 101 requirement randomly. Sometimes it works fine, sometimes it doesn't.

**Comment by DAQEM** [comment]
Strange, I think I've found a solution. when I'm done, I'll update both 1.19.2 and 1.18.2.

**Comment by jinkhya** [comment]
awesome !! thank you for your work :) 👍

**Comment by kiiriitsugu** [comment]
Great, looking foward to it.

**Comment by erazare** [comment]
this issue is no longer an issue as of 53.. however i have another one but not sure how to register it correctly.. the thing is.. you can use the tool to easily duplicate the tools...

**Comment by erazare** [comment]
ohi havent tested enough to notice the on/off misfunctionality.. i just saw it work on the server and assumed it did..

**Comment by jinkhya** [comment]
Hello, i saw you archived the jar however there's no other 1.19.2 versions and I'm using it in my modpack, and since it's archived only curseforge can download those. Some people are using linux and curseforge launcher is not an option. Could you please unarchive it? :)
Thanks in advance!

**Comment by erazare** [comment]
I would like it if you would unarchive .6.2 as well. I already have it in
my official live server and am now forced to redistribute the file for
people to play on my server.

**Comment by DAQEM** [comment]
0.6.2 will not be unarchived. 0.7 for 1.19.2 will be released soon.

**Comment by jinkhya** [comment]
Fair enough, ty for the heads-up!

**Comment by DAQEM** [comment]
0.7 for 1.19.2 is not live. 1.18.2 issue updates here: #39
