### ISSUE TITLE
[1.19] Immersive Engineering Ores can't be veinmined

### ISSUE THREAD

**Issue by jinkhya** [DAQEM/JobsPlus-Archive#38]
Hello,
It seems that Immersive Engineering ores can't be veinmined. 
Jobs 0.6.1
IE 9.0.0-153
forge 43.1.47

thanks in advance,
Jin

**Comment by jinkhya** [comment]
Powah ores either. Is there a tag that can be added to ores to add cross-mod compat?

**Comment by DAQEM** [comment]
Thank you for reporting.
