### ISSUE TITLE
[1.19.2]  Construction Tabe UI problems. 

### ISSUE THREAD

**Issue by ffuentesm** [DAQEM/JobsPlus-Archive#40]
For some reason, the crafting list on the right shows double items.  And the JEI menu is being compressed vertically instead of horizontally. 
![image](https://user-images.githubusercontent.com/44974827/200091675-c707a2c1-0f82-4cc8-93bb-3676891c20d3.png)

Also, could you add the "drag item from inventory" ability the recipe book has? 
So that when we click to craft an item from the list, if compatible items are available in the inventory, those items will be put in place. 

And could the "tier material" be changed? 
Lv 100 being emerald feels "easy" what about using Netherite Ingot for that tier of item? 
And maybe remove Gold and add copper as tier 1. 
So it would be copper -> Iron -> diamond -> Netherite

**Comment by DAQEM** [comment]
0.6.2 has been removed from CurseForge due to some issues. Please create a seperate issue for enhancements.
