### ISSUE TITLE
[Suggestion] Improvement changes

### ISSUE THREAD

**Issue by ffuentesm** [DAQEM/JobsPlus-Archive#41]
Could you add the "drag item from inventory" ability the recipe book has?
So that when we click to craft an item from the list, if compatible items are available in the inventory, those items will be put in place.

For the Experience Jar, could that oak planks be changed to accept any plank type? In case there is no oak around? Just use the wood_plank tag.
Also, could you add a Ctrl + Right Click to give 1 experience level per click? So that we can save on experience points? Since level 40 to 37 is very different from 20 to 17.

And could the "tier material" be changed?
Lv 100 being emerald feels "easy" what about using Netherite Ingot for that tier of item?
And maybe remove Gold and add copper as tier 1.
So it would be copper -> Iron -> diamond -> Netherite

**Comment by DAQEM** [comment]
Features have been added in 7074f75be046f43d8a7576d8a67738cf88097d20
