### ISSUE TITLE
[1.19.2 (0.7)] Client crash, hover over item with shift

### ISSUE THREAD

**Issue by erazare** [DAQEM/JobsPlus-Archive#42]
As of the latest update, client WILL crash if you hit SHIFT for more information on the Jobs+ tools. Tested on both CF Launcher and on GDLauncher. 43.1.47

**Comment by DAQEM** [comment]
This works fine for me on 43.1.47.
What version of JEI are you using?
Also, could you send the crash log using a [Gist](https://gist.github.com/)
![](https://i.imgur.com/sR70e60.gif)

**Comment by erazare** [comment]
so, that is NOT what i am referring to in your included gif. go to the Jobs+ menu, select a job then select the tools tab that you get for the job. now hover over one of those tools and hit SHIFT { for more information } and voila.. crash to client
tested now on CF Launcher, GD Launcher and MC Launcher... same issue.
its not my setup, .6.2 worked flawlessly when it was pulled, people just didn't understand the menu. I am not using JEI to get the information i am using your MOD to do so.

**Comment by erazare** [comment]
![2022-11-08_13 23 58](https://user-images.githubusercontent.com/92096/200645305-f49572f6-11cf-4909-b699-ca3052be0b1b.png)

**Comment by DAQEM** [comment]
This still works fine, in singleplayer and multiplayer. 
Could you please send me the crash log.
![](https://i.imgur.com/pCpUTeU.gif)

**Comment by kaffeekirsche** [comment]
Hello, I just had this error too. I pressed shift in the tooltip view. here is my crash log.

https://nopaste.net/SdSlJoYKyV

**Comment by DAQEM** [comment]
Thank you for the crash log. I'll post a fix on CurseForge in an hour or so.

**Comment by DAQEM** [comment]
Fixed by 604d3967ef6d0a363e79e3ba3c14397172eda2de
0.7.1 has been uploaded to CurseForge and will be available soon.

**Comment by erazare** [comment]
Will do, but it confuses me as to why it didn't do this with any previous
1.19 release

**Comment by DAQEM** [comment]
No need, issue has been solved already.
It didn't do it with other releases because they are other releases, and the code changed.
