### ISSUE TITLE
another crash... something to do with Jobs+ 

### ISSUE THREAD

**Issue by erazare** [DAQEM/JobsPlus-Archive#43]
i got no setup i have no idea HOW it occurred but going to assume one of the players hit jobs+ and it kicked out the following error.
[crash-2022-11-08_12.23.53-client.txt](https://github.com/DAQEM/JobsPlus/files/9965858/crash-2022-11-08_12.23.53-client.txt)

**Comment by erazare** [comment]
heavily crashing client now... every few times you perform any skill client crashes.. want all the crash reports for the past half hour?
it drops client pretty much every 5 or so skill actions. godforbid you stack dirt.. three blocks in succession and it drops.. EVERY SINGLE TIME. can you just Unarchive .6.2? IT works. sure there is a grammatical error about tools being 101st level, but you can still make them and still use them in 6.2 without the CONSTANT crashes.

**Comment by DAQEM** [comment]
0.6.2 DOESNT work. It has a quadratic duplication glitch.
You are currently using 0.7. Please use 0.7.1.

**Comment by erazare** [comment]
> 0.6.2 DOESNT work. It has a quadratic duplication glitch. You are currently using 0.7. Please use 0.7.1.

incorrect, i am using .6.2 On the server and re-distributing the .6.2 for my clients until you fix this. it is NOT broken, it works perfectly fine you are welcome to join my server at ANY time and see for yourself.
now.. if you have stopped it from CTD i will update it to the latest version, but do NOT tell me that it doesnt work because it works perfectly fine!  Yes, you can duplicate with it, and yes that is bad.. but Crash to Desktop every time you do ANYTHING is the definition of broken.. nonfunctional. people being able to cheat by manipulating the mod is an issue to be sure, but not game breaking.
