### ISSUE TITLE
Crashing server now.. have another log... 

### ISSUE THREAD

**Issue by erazare** [DAQEM/JobsPlus-Archive#46]
do you even test this stuff on server enviroment?
[crash-2022-11-09_10.46.09-server.txt](https://github.com/DAQEM/JobsPlus/files/9972705/crash-2022-11-09_10.46.09-server.txt)

reverting back to .6.2 again.. honestly kevin.. still the only version that doesnt crash client or server

**Comment by DAQEM** [comment]
Yes I am. I'm not even getting these errors. How do I recreate it?

0.6.2 is more broken than this one. Here is a gif of 0.6.2:
![](https://i.imgur.com/Ldtfu8H.gif)

**Comment by erazare** [comment]
yes there is a duplication error, yes, we ALL know that. but it DOESNT CRASH CLIENT OR SERVER. Listen man.. you could wrap a pile of textfiles in a zip and claim its a new update, doesnt mean you fixed anything. I agree .6.2 has errors but it WORKS.. nothing afterwards works in server enviroment.

**Comment by RageQuitAmy** [comment]
Honestly erazare, maybe you should learn how to code and fix it yourself if you aren't happy with it. I know how hard DAQEM works on this and he does test it out.

**Comment by erazare** [comment]
> Honestly erazare, maybe you should learn how to code and fix it yourself if you aren't happy with it. I know how hard DAQEM works on this and he does test it out.

oh believe me Amy, the thought has crossed my mind. however I do not wish to steal from the developer. I could have rewritten .6.2 rebranded it and re-released it as soon as this started and no one would be the wiser. that's not my ethics. stop SIMPing to the developer. we all agree its a great concept, no one is denying anything or trying to disturb anyone, but broken is broken, if you intend to keep the project fix it.. nothing simpler.. can't fix it abandon it and someone WILL fix it.

**Comment by erazare** [comment]
> Yes I am. I'm not even getting these errors. How do I recreate it?
> 
> 0.6.2 is more broken than this one. Here is a gif of 0.6.2: ![](https://camo.githubusercontent.com/31f677b4d4d76963ff92f2cdff98765a69f88d3f2f5f187099de3ad8968d77f1/68747470733a2f2f692e696d6775722e636f6d2f4c6474667538482e676966) [ ![68747470733a2f2f692e696d6775722e636f6d2f4c6474667538482e676966](https://camo.githubusercontent.com/31f677b4d4d76963ff92f2cdff98765a69f88d3f2f5f187099de3ad8968d77f1/68747470733a2f2f692e696d6775722e636f6d2f4c6474667538482e676966) ](https://camo.githubusercontent.com/31f677b4d4d76963ff92f2cdff98765a69f88d3f2f5f187099de3ad8968d77f1/68747470733a2f2f692e696d6775722e636f6d2f4c6474667538482e676966) [ ](https://camo.githubusercontent.com/31f677b4d4d76963ff92f2cdff98765a69f88d3f2f5f187099de3ad8968d77f1/68747470733a2f2f692e696d6775722e636f6d2f4c6474667538482e676966)

how do you recreate it? get on a server with say.. one or two others, play for about 3mins and you will see the rubber-banding as the client has trouble communicating with the server, then the client drops, the server gets stuck waiting for a response and then it drops. I might have been rash to suggest you are not testing, but i dont believe that you are testing this in a multiplayer envioroment.

**Comment by DAQEM** [comment]
Here is some proof of multiplayer testing for you ;)
![](https://i.imgur.com/gaItvlm.png)
