### ISSUE TITLE
(1.18.2) Jobs+ recipes quickmove crash

### ISSUE THREAD

**Issue by CalcipherD** [DAQEM/JobsPlus-Archive#47]
Minecraft Version: 1.18.2
Jobs+ Version: Jobsplus-0.4.0
JEI Version: JEI-1.18.2-9.7.2.273
Forge Version: 40.1.84
Modpack: Life in the Village 3

The issue I found is that whenever I go to create a Jobs+recipe, I use Quickmove to put it in my inventory (Shift-Left Click), it crashes the client. Server still runs fine.

Only Jobs+ recipes are affected, everything else works fine.

Crash report added below.

[crash-2022-11-12_13.17.30-client.txt](https://github.com/DAQEM/JobsPlus/files/9994228/crash-2022-11-12_13.17.30-client.txt)

**Comment by DAQEM** [comment]
Fixed by 07a69860100c2f20be8f5f728e90826380e5d765
