### ISSUE TITLE
Suggestion: Tetra (and possibly other modded tool) compatability

### ISSUE THREAD

**Issue by Gotyam** [DAQEM/JobsPlus-Archive#5]
Yet to test how many things it affects, but the vein miner power does not work when using a Tetra pickaxe, willing to bet Tinker's ones also don't work right. I would like to suggest letting the vein miner use any tool that is a pickaxe, or alternatively a config option to add custom entries as valid tools for vein-mining (would also be nice with a config to begin with), as Tetra might be the one not labling the tools right.

Obviously, using latest versions of both mods mentioned; Tetra 4.8.0 and Jobs+ 0.2.8.

**Comment by DAQEM** [comment]
Sorry for the very late reply, but this should be fixed now.
