### ISSUE TITLE
Hammering Soapstone from BYOG gives too much EXP

### ISSUE THREAD

**Issue by aNinjin** [DAQEM/JobsPlus-Archive#50]
Breaking soapstone with a hammer gives you massive experience drops.

Single block EXP:
![image](https://user-images.githubusercontent.com/106577745/201776157-44618e94-4477-4b5d-a46b-4e29101cb005.png)
Hammer EXP(9 Blocks):
![image](https://user-images.githubusercontent.com/106577745/201776330-c3e665fe-1822-4a9f-acea-7c6bf922e578.png)

**Comment by DAQEM** [comment]
Getting 23 EXP for 9 would be around 2.5 EXP per block. That's between stone and ores. That isn't too much right?

**Comment by aNinjin** [comment]
> 

I thought mining in 3x3 had draw backs like not getting the full amount of XP. When I was mining 3x3 on stone, I was only getting 2-3xp total. It's the same when you use the lumberjack axe on trees. You only get like 2xp for the whole tree. That's what I'm comparing it to.
