### ISSUE TITLE
3x3 Mining on servers not working?

### ISSUE THREAD

**Issue by aNinjin** [DAQEM/JobsPlus-Archive#53]
For some reason 3x3 mining isn't working on my server with 4 players. I was able to mine 3x3 when I was by myself but once someone logged in, I was unable to use my hammer or excavator. Now it doesn't matter and is not working at all.

Minecraft Version: 1.18.2
Jobs+ Version: 0.8.2

**Comment by DAQEM** [comment]
I found the cause of this issue. When you are using veinminer and you release the veinmine button before all the blocks are mined, the mod thinks you're still veinmining. For now, you can resolve this issue by restarting the server and holding the veinminer key until all the blocks are mined. In the meanwhile, I'm going to fix this issue.
