### ISSUE TITLE
[1.19.2 - 0.9] Vein mining ore only gives mining exp for first block

### ISSUE THREAD

**Issue by Xetaxheb** [DAQEM/JobsPlus-Archive#55]
Vein mining ore only gives mining exp for first block, so mining a coal ore vein only gives +5 exp versus mining it manually would give say 80~

This is with jobs+ powerup, haven't tested ore excavation/etc but by their nature they tend to run block break event on every block so maybe it works there? but worth checking

**Comment by RageQuitAmy** [comment]
Hi, is this only happening on a server or on single player also?

**Comment by Xetaxheb** [comment]
Singleplayer.

**Comment by RageQuitAmy** [comment]
I am on single player right now and I am getting no exp but I am getting iron ingots without auto smelt. On a server I was getting exp though which is really weird. I think the miner job is just having a rough time at the moment.

**Comment by DAQEM** [comment]
Fixed in JobsPlus 1.19.2 - 0.9.2
