### ISSUE TITLE
Hammer doesn't give mined ores

### ISSUE THREAD

**Issue by Zealoheart** [DAQEM/JobsPlus-Archive#58]
First time getting the Iron Hammer for Miner. (Patch 1.19.2)
When i mined coal, copper or Iron nodes with the iron hammer, it doesn't drop anything for me.
I do receive EXP as per normal but no drops. Even after switching back to Pickaxe it doesn't drop.

Minor workaround, had to restart the server to make me have drops. But i cant use the hammer, i have to stick with using pickaxe.
Unsure if this is a bug.

**Comment by RageQuitAmy** [comment]
Hi, I was just wondering if you get this issue on just servers or if you get it on single player also?

**Comment by Zealoheart** [comment]
So far ive only gotten it on server, i havent tested in singleplayer yet
________________________________

**Comment by RageQuitAmy** [comment]
Okay, I have been trying to replicate it for the last few days and after making my own server and leaving it on for some time, I had the same problem. The only 2 ways I could fix it was by restarting the server like you did and disabling ore vein miner and auto smelt ores. Hopefully with all this info it can be fixed but for now, all you can do is restart the server or disable those 2 power-ups while mining.

**Comment by Zealoheart** [comment]
Yep, thank you so much for figuring it out. But yeah, for now the quick workaround is restarting the server. Thanks again for the update!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by RageQuitAmy** [comment]
You're welcome!

**Comment by DAQEM** [comment]
Is this issue still occurring in JobsPlus 1.19.2 - 0.9.2?

**Comment by DAQEM** [comment]
Fixed in JobsPlus 1.19.2 - 0.9.2
