### ISSUE TITLE
Vein mining can let you mine ores the pickaxe shouldn't be able to

### ISSUE THREAD

**Issue by Gotyam** [DAQEM/JobsPlus-Archive#6]
If you vein mine starting on e.g. Iron or Coal ore using a stone pickaxe, then if gold, diamond (or modded) ores that your current pickaxe cannot normally mine, then the vein mining will ignore this and dig them up anyhow.

The fix I think would work best is to have vein mining only mine blocks of the same type as the one you start on (so vein mining a coal vein ONLY mines the coal, not the 100 other ores a big vein could potentially touch).

**Comment by DAQEM** [comment]
Fixed in latest version.
