### ISSUE TITLE
Double Drops when farming gives a carved pumpkin instead of a regular one as double-drop.

### ISSUE THREAD

**Issue by Friefingly** [DAQEM/JobsPlus-Archive#60]
When having the _Double Drops when Farming_ Ability on, if you destroy a pumpkin and you get double drops, the doubled drop will be a carved pumpkin instead of a regular one.

**Comment by DAQEM** [comment]
This is part of the "Better drops" powerup. It has a chance to drop a pie or a carved pumpkin.
