### ISSUE TITLE
[Suggestion] 1x1 mining option for tools

### ISSUE THREAD

**Issue by Dorilgey** [DAQEM/JobsPlus-Archive#62]
Hello! This mod is awesome! I do think it would be great if there was an option for the tools to only mine 1x1 block. Occasionally forgetting to crouch when trying to mine 1 block has led to breaking a ton of stuff by accident. (Apologies if this is not the spot for suggestions).

**Comment by Cacalotlcoatl** [comment]
I second this. An additional point is that if you are trying to build up high and using scaffolding or a jet pack, crouching makes you move down which makes targeting a single block to break rather difficult and a giant pain in the ass.
