### ISSUE TITLE
Mod conflict. Origins breaks the Smith superpower. 

### ISSUE THREAD

**Issue by RageQuitAmy** [DAQEM/JobsPlus-Archive#63]
When using the origins mod and Jobs+, the Smith superpower only works with Jobs+ items and not vanilla ones. It also doesn't work with other modded items. 

Version: JobsPlus 1.19.2-0.9.2
Origins Version: origins-forge- 1.19.2- 1.5.0.6-all

**Comment by DAQEM** [comment]
Sounds like an issue for Origins. I'm setting the items to unbreakable to vanilla way.
https://github.com/DAQEM/JobsPlus/blob/1.19.2/src/main/java/me/daqem/jobsplus/events/jobs/SmithEvents.java#L48
