### ISSUE TITLE
Spamming server logs and lagging

### ISSUE THREAD

**Issue by GarouKangur** [DAQEM/JobsPlus-Archive#71]
Minecraft: 1.19.2
Jobs+: 1.19.2-0.9.2
JEI: 1.19.2-forge-11.5.2.1007
Forge: 43.2.1

The Issue I found is:
Jobs+ has for some reason started to spam my friends server logs with "Server thread/[ERROR] [me.da.jo.JobsPlus/]: one"  and it causes the server to overload and lag a lot. 
![image](https://user-images.githubusercontent.com/124089428/215865577-d830fee8-50c9-4e36-9cfb-5b4b72e2fc96.png)

**Comment by DAQEM** [comment]
Please update to the latest version of Jobs+. Its fixed in 0.9.3 and later.
