### ISSUE TITLE
Extact EXP multilpier and other config to a more mutable file

### ISSUE THREAD

**Issue by WhiT-Eboard** [DAQEM/JobsPlus-Archive#73]
I found it inconvenient for me to change EXP multiplier as I have to recompile the whole project. So is there a chance that these conifgs can store in a .json file, .xml file or .properties file?

**Comment by DAQEM** [comment]
They are already in a serverconfig .toml file in the world > serverconfigs folder.

**Comment by WhiT-Eboard** [comment]
Really appreciate it.
