### ISSUE TITLE
[1.18.2] Miner's Hammer eats away one block

### ISSUE THREAD

**Issue by ffuentesm** [DAQEM/JobsPlus-Archive#8]
Forge: 40.1.0
jobsplus-0.3.0.jar
ImmersiveEngineering-1.18.2-8.0.1-147.jar

When I try to use the Miner's hammer to break a multiblock contraption from Immersive Engineering, it only returns 8 blocks instead of 9.

**Comment by DAQEM** [comment]
Fixed by 07a69860100c2f20be8f5f728e90826380e5d765
