### ISSUE TITLE
config idea

### ISSUE THREAD

**Issue by itsdeadfrosty** [DAQEM/JobsPlus-Archive#86]
Can we get config to toggle what gear or abilities we want? or just a nerf to enchanter? Being able to extract enchantments from gear As an enchanter Is really overpowered In my opinion. It would be really nice if there was some kind of option where You could toggle it so it's kind of a random toss up of whether you get one in enchantment. or another. And that you would always get it at tier one, so you had to collect a couple of books to put them together to get your higher level enchantment instead of just Using like apotheosis and then getting really amazing drops from some random zombie and then having terribly OP gear Right away, pretty much.

**Comment by itsdeadfrosty** [comment]
or even just putting the enchant extracts as a lvl 100 perk. or maybe make it level as you go so you have to reach level 25/50/75/100 to go from getting one random enchantment to the enchantment that you desire, to getting it at a higher level, to getting exactly what was on the item. etc

**Comment by DAQEM** [comment]
Thank you for your comment regarding the enchantment system in the game. I appreciate your suggestion of having a toggle option enchnaters abilities, or even a nerf of the enchanter job. I understand that the ability to extract enchantments from gear can be overpowered and unbalanced in the game.

I am currently working on a replacement mod that aims to improve upon the original system. You can find more information about it at https://github.com/DAQEM/JobsPlusRemastered. Your suggestion is a good one, and I will definitely consider implementing it in the new mod.

Thank you for taking the time to provide feedback and for your interest in my project.

**Comment by itsdeadfrosty** [comment]
Thank you I’ll look into the modOn May 5, 2023, at 18:10, Kevin ***@***.***> wrote:﻿
Thank you for your comment regarding the enchantment system in the game. I appreciate your suggestion of having a toggle option enchnaters abilities, or even a nerf of the enchanter job. I understand that the ability to extract enchantments from gear can be overpowered and unbalanced in the game.
I am currently working on a replacement mod that aims to improve upon the original system. You can find more information about it at https://github.com/DAQEM/JobsPlusRemastered. Your suggestion is a good one, and I will definitely consider implementing it in the new mod.
Thank you for taking the time to provide feedback and for your interest in my project.
