### ISSUE TITLE
Some sort of "Corpse mod" like thing spawned on death.

### ISSUE THREAD

**Issue by itsdeadfrosty** [DAQEM/JobsPlus-Archive#87]
jobsplus-1.18.2-0.8.2.jar

I already have the corpse mod enabled. Is there some way to disable this floaty thing? Like can we get some configs?

![2023-05-13_13 46 43](https://github.com/DAQEM/JobsPlus/assets/132015237/1a7c71b7-edfd-4036-884d-bdb52ef0bdb4)

**Comment by DAQEM** [comment]
That is not Jobs+

**Comment by itsdeadfrosty** [comment]
I have realized that. Thank you. It is the totem of holding from the Quark Oddities mod.
