### ISSUE TITLE
Alchemist Potion Effect Conflicts

### ISSUE THREAD

**Issue by Jorgee9001** [DAQEM/JobsPlus-Archive#9]
On our server, we have several mods that add their own way of acquiring some of the same potion effects given by the alchemist profession. However, unless the individual is an alchemist, they are blocked from having the effect. 

I would suggest renaming/modifying these effects so that they are functionally similar, but do not conflict with the mods that add the base vanilla effect. That way the player can still have the effect if they choose to not be an alchemist.

Alternatively, a config where we can allow non-alchemists to have these effects would be appreciated.

**Comment by SeanChengN** [comment]
Same as me. The vanilla potions can't be used either, like the lucky effect. And conflicts with all mods that provide lucky effects, such as [Enhanced Celestials](https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials)' blue moon.
![2022-06-04_14 56 27](https://user-images.githubusercontent.com/20624068/171988581-24bcc54d-9481-4a94-8d3b-1a367327c94c.png)

**Comment by jollyroger182** [comment]
Agreed. Dimensional Dungeons gives Lingering Potions of Luck sometimes as loot, and we cannot use that. Beacons can also give Haste II which is also banned.

**Comment by DAQEM** [comment]
I'm sorry you guys had to wait so long. But I finally added a config option of it.
